apiVersion: skaffold/v2beta11
kind: Config
  #build:
  #  artifacts:
  #  - image: mongo
  #    context: .
  #    docker:
  #      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s-manifests/mongodb/*.yaml
portForward:
  - resourceType: service
    resourceName: mongodb-service
    namespace: default
    port: 27017
    localPort: 27017
